### ISSUE TITLE
Support host-meta lookups

### ISSUE THREAD

**Issue by fauno** [hyphacoop/social.distributed.press#15]
By using host-meta URI templates, it's possible to generate alternate webfingers.  We're trying this for localization (one Actor per language) but could also be used to generate per-author Actors or other metadata (type, hashtag, etc).

The following works on a Mastodon search but throws a 404 error on the Social Inbox for the missing WebFinger:

https://0xacab.org/sutty/jekyll/jekyll-activitypub/-/issues/4#note_1136809

Error:

```
Cannot fetch webmention data from https://probandoactivitypub3.sutty.local/.well-known/webfinger?resource=acct:es@probandoactivitypub3.sutty.local: http status 404 - <html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
```

If the Social Inbox performs host-meta lookups, it'll be possible to apply different URI templates and support multiple actors per site.

**Edit:** Make more clear what's the action to be taken

**Comment by fauno** [comment]
Ping @akhileshthite is this something you can implement?

**Comment by fauno** [comment]
@RangerMauve @akhileshthite if this is easy for you to implement, I could have `@es@sutty.nl` and `@en@sutty.nl` ready for next week's presentation

**Comment by fauno** [comment]
For instance, mastodon fallbacks to /.well-known/host-meta when /.well-known/webfinger is missing

https://github.com/mastodon/mastodon/blob/main/app/lib/webfinger.rb#L55

**Comment by RangerMauve** [comment]
This should be good to go
