### ISSUE TITLE
Sometimes remote instances require all requests to be signed

### ISSUE THREAD

**Issue by fauno** [hyphacoop/social.distributed.press#16]
(We're asking the instance admin if we can name it publically)

We're testing remote follows from a Mastodon+Glitch v4.1.3 instance and it fails because it requires signed requests to fetch Actors.  We can reproduce by `curl`ing the follower profile:

```sh
curl --header "Accept: application/activity+json" FOLLOWER_PROFILE_URL | jq .
```

Returns:

```json
{
  "error": "Request not signed"
}
```

**Comment by fauno** [comment]
It's related to this feature: 

https://docs.joinmastodon.org/admin/config/#authorized_fetch

https://fedi.tips/authorized-fetch/

**Comment by fauno** [comment]
Action: All requests should be signed, or feature detection is needed to discover which instances require signed requests

**Comment by RangerMauve** [comment]
Cool, yes that is very doable.

**Comment by RangerMauve** [comment]
@akhileshthite Basically we need to replace the call to `this.fetch` with `this.signedFetch`

**Comment by akhileshthite** [comment]
> @akhileshthite Basically we need to replace the call to `this.fetch` with `this.signedFetch`
> 
> https://github.com/hyphacoop/social.distributed.press/blob/initial/src/server/apsystem.ts#L187

Do we need a test `getActor fetches and returns the actor profile using signedFetch` for this?

**Comment by RangerMauve** [comment]
Merged into latest `initial` branch!
