### ISSUE TITLE
feat: auto-accept follow requests

### ISSUE THREAD

**Issue by akhileshthite** [hyphacoop/social.distributed.press#18]
When I created a new blog on Sutty and had it create a Fediverse account, I noticed that it required an approval for new followers.

_Originally posted by @maisutton in https://github.com/hyphacoop/distributed-press-organizing/issues/87#issuecomment-1787765033_

**Comment by akhileshthite** [comment]
> When I created a new blog on Sutty and had it create a Fediverse account, I noticed that it required an approval for new followers.
> 
> _Originally posted by @maisutton in [hyphacoop/distributed-press-organizing#87 (comment)](https://github.com/hyphacoop/distributed-press-organizing/issues/87#issuecomment-1787765033)_

For this change, in the `ingestActivity` method, we should bypass moderation for Follow type activities and approve them directly, correct? Should I send a PR for this @RangerMauve?

```javascript
  async ingestActivity (fromActor: string, activity: APActivity): Promise<void> {
    const activityId = activity.id

    // TODO: handle array of string case and nested object
    if (typeof activityId !== 'string') {
      throw new Error('Activities must contain an ID')
    }

    const activityActor = activity.actor

    // TODO: handle array of string case and nested object
    if (typeof activityActor !== 'string') {
      throw new Error('Activities must contain an actor string')
    }

    // Handle Follow activities by automatically approving them
    if (activity.type === 'Follow') {
      // No need for moderation, immediately approve the Follow activity
      await this.approveActivity(fromActor, activityId)
    } else {
      // For all other activities, proceed with moderation
      const mention = await this.actorToMention(activityActor)
      const moderationState = await this.modCheck.check(mention, fromActor)

      // Adding activity to the inbox should happen irrespective of moderation state
      // TODO: trigger hooks
      const actorStore = this.store.forActor(fromActor)
      await actorStore.inbox.add(activity)

      // Handle moderation states for other activities
      if (moderationState === BLOCKED) {
        await this.rejectActivity(fromActor, activityId)
      } else if (moderationState === ALLOWED) {
        await this.approveActivity(fromActor, activityId)
      } else {
        await this.hookSystem.dispatchModerationQueued(fromActor, activity)
      }
    }
  }
```

**Comment by fauno** [comment]
IIRC @RangerMauve we talked about allowlisting every follow request (that's isn't superseded by the default blocklist) until we have a moderation queue interface implemented, is that correct?

**Comment by fauno** [comment]
I mean, we've been using the plugin without having to accept follow requests so far

**Comment by fauno** [comment]
Related to https://github.com/hyphacoop/social.distributed.press/issues/53

**Comment by RangerMauve** [comment]
Seems to be done?
