### ISSUE TITLE
Blocklist is replaced with new data

### ISSUE THREAD

**Issue by fauno** [hyphacoop/social.distributed.press#37]
I'm testing the blocklist API client and I can get the current list and send new items, but when I get the list again, the new items completely replaced the previous list. I assumed they were appended instead:

![image](https://github.com/hyphacoop/social.distributed.press/assets/468204/3a97d62c-2436-49a3-806f-f25fb44e3ba2)

**Comment by RangerMauve** [comment]
Oh. It might be due to the syntax not being correct. Each entry should be in `@username@domain.com` syntax with the username being replaceable with `*` like `@*@domain.com`.

We should be throwing an error when the syntax is wrong.

**Comment by fauno** [comment]
I'll check later then :)

**Comment by RangerMauve** [comment]
is this still an issue?

**Comment by fauno** [comment]
I confirm this is fixed!
