### ISSUE TITLE
Remove `@*@*` from default allowlist

### ISSUE THREAD

**Issue by fauno** [hyphacoop/social.distributed.press#54]
The CMS will auto-approve follows but moderates other activities.

- [ ] Remove `@*@*` from general allowlist
- [ ] Add `@*@*` to announcements
- [ ] Add `@*@*` to sites not managed by the CMS

**Comment by fauno** [comment]
Related to #53

**Comment by fauno** [comment]
@RangerMauve also gardenfence is not required by default on sutty-managed websites, could you remove it too?

**Comment by RangerMauve** [comment]
Mind opening a separate issue for the gardenfence stuff?

The allow all rule has been removed
