### ISSUE TITLE
Tildes in activity IDs are not parsed correctly

### ISSUE THREAD

**Issue by fauno** [hyphacoop/social.distributed.press#67]
While working on https://github.com/hyphacoop/distributed-press-organizing/issues/158 I noticed some replies collection return 404 and others not. It seems the router has an issue with tilde characters.

This doesn't work:

https://social.distributed.press/v1/@sutty@sutty.nl/inbox/replies/https%3A%2F%2Fsutty.nl%2Flanzamiento-nueva-funci%25C3%25B3n-de-moderaci%25C3%25B3n-para-los-sitios-conectados-al-fediverso.jsonld

This works:

https://social.distributed.press/v1/@sutty@sutty.nl/inbox/replies/https%3A%2F%2Fsutty.nl%2Fsutty-visita-hackbo.jsonld

**Comment by RangerMauve** [comment]
That's so unexpected. :/ Maybe we should use a different encoding?

**Comment by fauno** [comment]
i'm not sure if it's an issue with fastify or leveldb?

**Comment by RangerMauve** [comment]
99% sure it's in fastify. Probs something to do with unicode

**Comment by sutty-coop** [comment]
Fauno and Mauve can hack on this next week
