### ISSUE TITLE
Activities likes and shares collection return 404

### ISSUE THREAD

**Issue by fauno** [hyphacoop/social.distributed.press#93]
I think it should return an empty collection even if the activity doesn't exist on the database. This activity has been notified to the outbox already.

```
id: https://distributed.press/2024/10/29/escape-the-algorithm-meet-social-reader-your-personal-feed.jsonld
base64: aHR0cHM6Ly9kaXN0cmlidXRlZC5wcmVzcy8yMDI0LzEwLzI5L2VzY2FwZS10aGUtYWxnb3JpdGhtLW1lZXQtc29jaWFsLXJlYWRlci15b3VyLXBlcnNvbmFsLWZlZWQuanNvbmxk
likes: https://social.distributed.press/v1/@distributed@distributed.press/inbox/replies/aHR0cHM6Ly9kaXN0cmlidXRlZC5wcmVzcy8yMDI0LzEwLzI5L2VzY2FwZS10aGUtYWxnb3JpdGhtLW1lZXQtc29jaWFsLXJlYWRlci15b3VyLXBlcnNvbmFsLWZlZWQuanNvbmxk
```

```
{"level":30,"time":1733255958776,"pid":643733,"hostname":"srv2","reqId":"req-5he","msg":"Route GET:/v1
/@distributed@distributed.press/inbox/likes/aHR0cHM6Ly9kaXN0cmlidXRlZC5wcmVzcy8yMDI0LzEwLzI5L2VzY2FwZS10aGUtYWxnb3JpdGhtLW1lZXQtc29jaWFsLXJlYWRlci15b3VyLXBlcnNvbmFsLWZlZWQuanNvbmxk not found"}
```

**Comment by fauno** [comment]
by querying the inbox via the ruby client i can find that this particular id doesn't have any interactions. this is from our console:

```ruby
site = Site.find_by name: "distributed.press."
items = site.social_inbox.client.get(endpoint: "/v1/@distributed@distributed.press/inbox?limit=1000")['orderedItems']
items.select { |x| x['object'] == 'https://distributed.press/2024/10/29/escape-the-algorithm-meet-social-reader-your-personal-feed.jsonld' } # empty array
items.select { |x| x['type'] == 'Like' }.map { |x| x['object'] } # 16 likes on 10 activities
```

i think the error is that activities without interactions throw a 404 instead of an empty collection

**Comment by RangerMauve** [comment]
It looks like it's breaking when the ID is over 100 chars.

E.g. this works [with 98 chars](https://social.distributed.press/v1/@distributed@distributed.press/inbox/likes/aHR0cHM6Ly9kaXN0cmlidXRlZC5wcmVzcy8yMDI0LzEwLzI5L2VzY2FwZS10aGUtYWxnb3JpdGhtLW1lZXQtc29jaWFsLXJlYW) and this breaks [with 101 chars](aHR0cHM6Ly9kaXN0cmlidXRlZC5wcmVzcy8yMDI0LzEwLzI5L2VzY2FwZS10aGUtYWxnb3JpdGhtLW1lZXQtc29jaWFsLXJlYWaaa)


Might be an issue with fastify

**Comment by RangerMauve** [comment]
https://github.com/fastify/fastify/blob/main/docs/Reference/Server.md#maxparamlength

Might be this

**Comment by RangerMauve** [comment]
Gonna dobule it to 256

**Comment by fauno** [comment]
yeah it works now, should i add a warning client-side? i wonder how we'll deal with longer than 256 char ids :P
